<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HSG16HN" ignored="0" name="Retry Logic test" tests="7" failures="1" timestamp="28 Feb 2020 15:47:59 GMT" time="0.047" errors="0">
  <testcase name="Test1" time="0.0" classname="com.qa.tests.MyTest"/>
  <testcase name="Test2" time="0.0" classname="com.qa.tests.MyTest"/>
  <testcase name="Test3" time="0.0" classname="com.qa.tests.MyTest">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.0" classname="com.qa.tests.MyTest">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.0" classname="com.qa.tests.MyTest">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.0" classname="com.qa.tests.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.tests.MyTest.Test3(MyTest.java:29)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" time="0.0" classname="com.qa.tests.MyTest"/>
</testsuite> <!-- Retry Logic test -->
